export const Musics = [
  {
    title: 'FCK IT',
    artist: 'VLXX x Xxtasy',
    src: 'https://beardbarnmusicbucket.s3.amazonaws.com/The+Wild+Horse',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '03:12',
  },
  {
    title: 'Ice on My Neck',
    artist: 'VLXX',
    src: 'https://beardbarnmusicbucket.s3.amazonaws.com/The+Wild+Horse',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:03',
  },
  {
    title: 'Drug',
    artist: 'Xxtasy (ft. VLXX)',
    src: 'https://30.filelu.com/d/wz3mbwdnjqqnjjtanom4u35wr3nusgumltq2gvowngxfyg6e57beoxmvt7vmtvzkr67lshvg/audio3.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: 'https://open.spotify.com/track/67OU35nqn8GoIWHYbwjPRR',
    itunes: '',
    soundcloud: 'https://soundcloud.com/xxtasy-music/drug-feat-vlxx',
    duration: '02:32',
  },
  {
    title: 'Evimə apar',
    artist: 'VLXX (ft. Xxtasy)',
    src: 'https://30.filelu.com/d/wz3ntwdnjqqnjjtanom5437fzszqpqe33y2idqtb436caa6ytxblnyyan3yxyj4wog2bjxdx/audio4.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:44',
  },
  {
    title: 'Yelləncək',
    artist: 'VLXX (ft. Xxtasy)',
    src: 'https://30.filelu.com/d/wz3nxwdnjqqnjjtanom54i7otpag6hr4ch46xwbownf7w3ve6fxlklstuwxfffspwbsm72xd/audio5.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:44',
  },
  {
    title: 'London',
    artist: 'Xxtasy',
    src: 'https://30.filelu.com/d/wz3nzwdnjqqnjjtanom4u653znqwssyxt4cq5hk42d2wybiibr46kzqzoax23t2minxcdkfz/audio6.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:57',
  },
  {
    title: 'Get',
    artist: 'VLXX',
    src: 'https://30.filelu.com/d/wz3n3wdnjqqnjjtanomym45xraz3hxqsauhxho3lg6ams3mcpcf5aixjfxwlgvu525xacqv7/audio7.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:05',
  },
  {
    title: 'De mənə',
    artist: 'VLXX (ft. Xxtasy)',
    src: 'https://32.filelu.com/d/rb3n7wdnjqqnjjtanom4uyp2setklquezfcivdgcck2mr73mah4bmr5xiijgu3okl3n4uemc/audio8.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:58',
  },
  {
    title: 'Hüzur (demo)',
    artist: 'VLXX',
    src: 'https://32.filelu.com/d/rb3nbwdnjqqnjjtanomy24f2y4essnknyz557frqwfke252aa2csdz6sxwsrwenjzmeu5byy/audio9.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:17',
  },
  {
    title: 'Maşallah',
    artist: 'Xxtasy x VLXX',
    src: 'https://32.filelu.com/d/rb3nfwdnjqqnjjtanom4oz7btj6n4rei3anyeldxb27clqr2xmgkyeryp23hdj4o6bug2cmo/audio10.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=48YpvVvAEDc',
    spotify: 'https://open.spotify.com/track/7rbGKOxHUVw71AshAqpUXs',
    itunes: 'https://music.apple.com/fm/album/ma%C5%9Fallah-single/1587119944',
    soundcloud: 'https://soundcloud.com/xxtasy-music/ma-allah',
    duration: '03:20',
  },
  {
    title: 'Passion',
    artist: 'Xxtasy x SVBHI x Rasheed',
    src: 'https://32.filelu.com/d/rb3nhwdnjqqnjjtanom4kyvttdbpnslbpl5ao2yhpw35vs4ubdkbn5cqhitqyxsy5dbreaqc/audio11.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=70JQzIs4Ve0',
    spotify: 'https://open.spotify.com/track/1up8TJt7ou5qLQCrYkBJUS',
    itunes: '',
    soundcloud:
      'https://soundcloud.com/xxtasy-music/passion-feat-svbhi-rasheed',
    duration: '02:44',
  },
  {
    title: 'Vice City',
    artist: 'Tibu (ft. Rasheed, Xxtasy)',
    src: 'https://32.filelu.com/d/rb3njwdnjqqnjjtanom5ijvsy5ih7sr4qvdoufvuibqpmnehq34ffvviovfjstycenhormgf/audio12.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=83o9iYDCLQ0',
    spotify: 'https://open.spotify.com/track/4vvHKjOxtMMOyLEk9SqVwT',
    itunes:
      'https://music.apple.com/us/album/vice-city-feat-rasheed-xxtasy/1622217978?i=1622217985',
    soundcloud: '',
    duration: '03:34',
  },
  {
    title: 'Telefona bax (demo)',
    artist: 'VLXX x Xxtasy',
    src: 'https://32.filelu.com/d/rb3nlwdnjqqnjjtanom5mivwt2xberw7p66czc5b3tencrmlkvefsixt5zgr2l55h2nbtkn3/audio13.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '01:55',
  },
  {
    title: 'Ulduzlararası (demo)',
    artist: 'VLXX x Xxtasy',
    src: 'https://32.filelu.com/d/rb3nnwdnjqqnjjtanom4qlxltnwjdftk3n5mzppjs7kyweutdaaewrnqytcr6ibojeyjcdsz/audio14.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:17',
  },
  {
    title: 'Next Location',
    artist: 'VLXX',
    src: 'https://32.filelu.com/d/rb3npwdnjqqnjjtanom52zpqsghrufo65rxexnxmpxnmkb2pot34cmvrdocrmavqzcf2ar5q/audio15.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:06',
  },
  {
    title: 'Kim var orda? (demo)',
    artist: 'VLXX x Nat',
    src: 'https://32.filelu.com/d/rb3krwdnjqqnjjtanom5s35uspwj27tuzdyfmm2prksoytys3treuctpa3btn27b3hi2rc53/audio16.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '01:50',
  },
  {
    title: 'Bad Wave (demo)',
    artist: 'Xxtasy x VLXX',
    src: 'https://32.filelu.com/d/rb3ktwdnjqqnjjtanom5e7xgyzlguf6oa67vdxpylqgsvavfezpild44rm6cr4aekzsdczvj/audio17.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '03:37',
  },
];
