export const Musics = [
  {
    title: 'FCK IT',
    artist: 'VLXX x Xxtasy',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio1.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '03:12',
  },
  {
    title: 'Ice on My Neck',
    artist: 'VLXX',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio2.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:03',
  },
  {
    title: 'Drug',
    artist: 'Xxtasy (ft. VLXX)',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio3.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: 'https://open.spotify.com/track/67OU35nqn8GoIWHYbwjPRR',
    itunes: '',
    soundcloud: 'https://soundcloud.com/xxtasy-music/drug-feat-vlxx',
    duration: '02:32',
  },
  {
    title: 'Evimə apar',
    artist: 'VLXX (ft. Xxtasy)',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio4.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:44',
  },
  {
    title: 'Yelləncək',
    artist: 'VLXX (ft. Xxtasy)',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio5.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:44',
  },
  {
    title: 'London',
    artist: 'Xxtasy',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio6.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:57',
  },
  {
    title: 'Get',
    artist: 'VLXX',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio7.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:05',
  },
  {
    title: 'De mənə',
    artist: 'VLXX (ft. Xxtasy)',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio8.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:58',
  },
  {
    title: 'Hüzur (demo)',
    artist: 'VLXX',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio9.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:17',
  },
  {
    title: 'Maşallah',
    artist: 'Xxtasy x VLXX',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio10.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=48YpvVvAEDc',
    spotify: 'https://open.spotify.com/track/7rbGKOxHUVw71AshAqpUXs',
    itunes: 'https://music.apple.com/fm/album/ma%C5%9Fallah-single/1587119944',
    soundcloud: 'https://soundcloud.com/xxtasy-music/ma-allah',
    duration: '03:20',
  },
  {
    title: 'Passion',
    artist: 'Xxtasy x SVBHI x Rasheed',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio11.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=70JQzIs4Ve0',
    spotify: 'https://open.spotify.com/track/1up8TJt7ou5qLQCrYkBJUS',
    itunes: '',
    soundcloud:
      'https://soundcloud.com/xxtasy-music/passion-feat-svbhi-rasheed',
    duration: '02:44',
  },
  {
    title: 'Vice City',
    artist: 'Tibu (ft. Rasheed, Xxtasy)',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio12.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=83o9iYDCLQ0',
    spotify: 'https://open.spotify.com/track/4vvHKjOxtMMOyLEk9SqVwT',
    itunes:
      'https://music.apple.com/us/album/vice-city-feat-rasheed-xxtasy/1622217978?i=1622217985',
    soundcloud: '',
    duration: '03:34',
  },
  {
    title: 'Telefona bax (demo)',
    artist: 'VLXX x Xxtasy',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio13.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '01:55',
  },
  {
    title: 'Ulduzlararası (demo)',
    artist: 'VLXX x Xxtasy',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio14.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:17',
  },
  {
    title: 'Next Location',
    artist: 'VLXX',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio15.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:06',
  },
  {
    title: 'Kim var orda? (demo)',
    artist: 'VLXX x Nat',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio16.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '01:50',
  },
  {
    title: 'Bad Wave (demo)',
    artist: 'Xxtasy x VLXX',
    src: 'https://github.com/YusifHuseynzadeh/KingsleyMusic/raw/main/audio17.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '03:37',
  },
];
