export const Musics = [
  {
    title: 'FCK IT',
    artist: 'VLXX x Xxtasy',
    src: '/static/media/audio1.a051a7f11ad34a2164cd.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '03:12',
  },
  {
    title: 'Ice on My Neck',
    artist: 'VLXX',
    src: '/static/media/audio2.fc062a0d43f9ed7e2257.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:03',
  },
  {
    title: 'Drug',
    artist: 'Xxtasy (ft. VLXX)',
    src: '/static/media/audio3.24c691fc1ab4b22d6bf5.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: 'https://open.spotify.com/track/67OU35nqn8GoIWHYbwjPRR',
    itunes: '',
    soundcloud: 'https://soundcloud.com/xxtasy-music/drug-feat-vlxx',
    duration: '02:32',
  },
  {
    title: 'Evimə apar',
    artist: 'VLXX (ft. Xxtasy)',
    src: '/static/media/audio4.f1d474b76646857517a4.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:44',
  },
  {
    title: 'Yelləncək',
    artist: 'VLXX (ft. Xxtasy)',
    src: '/static/media/audio5.8ce0fe25dede772aad0a.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:44',
  },
  {
    title: 'London',
    artist: 'Xxtasy',
    src: '/static/media/audio6.8e6fe8b21ad5f4c3f7c4.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:57',
  },
  {
    title: 'Get',
    artist: 'VLXX',
    src: '/static/media/audio7.0856e37e298ceec7bbe0.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:05',
  },
  {
    title: 'De mənə',
    artist: 'VLXX (ft. Xxtasy)',
    src: '/static/media/audio8.bb69a4b5f7598a4b50dc.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:58',
  },
  {
    title: 'Hüzur (demo)',
    artist: 'VLXX',
    src: '/static/media/audio9.850c7fb212ca28482161.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:17',
  },
  {
    title: 'Maşallah',
    artist: 'Xxtasy x VLXX',
    src: '/static/media/audio10.5b8456bfe40beb4791cb.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=48YpvVvAEDc',
    spotify: 'https://open.spotify.com/track/7rbGKOxHUVw71AshAqpUXs',
    itunes: 'https://music.apple.com/fm/album/ma%C5%9Fallah-single/1587119944',
    soundcloud: 'https://soundcloud.com/xxtasy-music/ma-allah',
    duration: '03:20',
  },
  {
    title: 'Passion',
    artist: 'Xxtasy x SVBHI x Rasheed',
    src: '/static/media/audio11.474fbb80dfce4e4e0073.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=70JQzIs4Ve0',
    spotify: 'https://open.spotify.com/track/1up8TJt7ou5qLQCrYkBJUS',
    itunes: '',
    soundcloud:
      'https://soundcloud.com/xxtasy-music/passion-feat-svbhi-rasheed',
    duration: '02:44',
  },
  {
    title: 'Vice City',
    artist: 'Tibu (ft. Rasheed, Xxtasy)',
    src: '/static/media/audio12.931c76a6ec20520a3b0a.mp3',
    progress: 0,
    length: 0,
    youtube: 'https://www.youtube.com/watch?v=83o9iYDCLQ0',
    spotify: 'https://open.spotify.com/track/4vvHKjOxtMMOyLEk9SqVwT',
    itunes:
      'https://music.apple.com/us/album/vice-city-feat-rasheed-xxtasy/1622217978?i=1622217985',
    soundcloud: '',
    duration: '03:34',
  },
  {
    title: 'Telefona bax (demo)',
    artist: 'VLXX x Xxtasy',
    src: '/static/media/audio13.fbc3645d3cb7bea90da0.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '01:55',
  },
  {
    title: 'Ulduzlararası (demo)',
    artist: 'VLXX x Xxtasy',
    src: '/static/media/audio14.c3b38207a00e15b4e915.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:17',
  },
  {
    title: 'Next Location',
    artist: 'VLXX',
    src: '/static/media/audio15.40165bf55875e3f1888b.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '02:06',
  },
  {
    title: 'Kim var orda? (demo)',
    artist: 'VLXX x Nat',
    src: '/static/media/audio16.340dd0ed52748afa35c4.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '01:50',
  },
  {
    title: 'Bad Wave (demo)',
    artist: 'Xxtasy x VLXX',
    src: '/static/media/audio17.9daf964024485db1bb5b.mp3',
    progress: 0,
    length: 0,
    youtube: '',
    spotify: '',
    itunes: '',
    soundcloud: '',
    duration: '03:37',
  },
];
